services:
  ollama:
    image: ollama/ollama:0.6.8
    ports:
      - "11434:11434"
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/bin/bash", "-c", "/bin/ollama serve & pid=$!; sleep 5; echo '🔴 Retrieve Ollama models...'; ollama pull qwen3:14b; ollama pull nomic-embed-text; echo '🟢 Done!'; touch /tmp/models_ready; wait $pid"]
    healthcheck:
      test: [ "CMD-SHELL", "test -f /tmp/models_ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 10s
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ollama-network
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.13.0
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - qdrant-data:/qdrant/storage
networks:
  ollama-network:
    external: false
volumes:
  ollama-data:
    name: ollama-data
  qdrant-data:
    name: qdrant-data
