server.port: 8081
spring:
  ai.mcp.server:
    name: mcp-server
    version: 0.0.1
    type: SYNC
  application.name: mcp-server
  datasource:
    url: jdbc:postgresql://localhost:5342/mcp-server
    username: gilles
    password: password
  liquibase.change-log: classpath:/db/changelog/db.changelog-master.yml
  threads.virtual.enabled: true

