services:
  postgresql:
    container_name: postgresql
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_DB: mcp-server
      POSTGRES_USER: gilles
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
volumes:
  postgresql-data:
    name: postgresql-data
